services:
  postgres:
    image: postgres:16-alpine
    container_name: ugb-postgres
    environment:
      POSTGRES_DB: ugb_banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  nodered:
    image: nodered/node-red
    container_name: ugb-nodered
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
  node_red_data:
